<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PostTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $posts = [
            [
                'title' => 'La Ciudad de los Engranajes Silenciosos',
                'author_name' => 'Silas Blackwood',
                'content' => 'En una metrópolis steampunk impulsada por vapor, un inventor descubre un secreto que podría detener el tiempo.',
                'poster' => 'https://placehold.co/400x600/4A5568/FFFFFF/png?text=Engranajes',
                'habilitated' => true,
                'stars' => 4,
                'category_id' => 1,
                'created_at' => Carbon::now()->subDays(31),
                'updated_at' => Carbon::now()->subDays(31),
            ],
            [
                'title' => 'El Imperio de Sal y Arena',
                'author_name' => 'Amara Khalid',
                'content' => 'Una novela histórica sobre las rutas comerciales de la antigüedad, llena de intriga política y aventuras en el desierto.',
                'poster' => 'https://placehold.co/400x600/D97706/FFFFFF/png?text=Imperio+de+Sal',
                'habilitated' => true,
                'stars' => 5,
                'category_id' => 4,
                'created_at' => Carbon::now()->subDays(32),
                'updated_at' => Carbon::now()->subDays(32),
            ],
            [
                'title' => 'Psicología de la Decisión',
                'author_name' => 'Dr. Evelyn Reed',
                'content' => 'Un análisis profundo de los sesgos cognitivos que guían nuestras elecciones diarias. Fascinante y revelador.',
                'poster' => 'https://placehold.co/400x600/059669/FFFFFF/png?text=Psicologia',
                'habilitated' => true,
                'stars' => 4,
                'category_id' => 2,
                'created_at' => Carbon::now()->subDays(33),
                'updated_at' => Carbon::now()->subDays(33),
            ],
            [
                'title' => 'El Ladrón de Recuerdos',
                'author_name' => 'Finn O\'Connell',
                'content' => 'Un detective con la habilidad de revivir los recuerdos de otros debe resolver un caso que amenaza su propia mente.',
                'poster' => 'https://placehold.co/400x600/7C3AED/FFFFFF/png?text=Ladron+Recuerdos',
                'habilitated' => true,
                'stars' => 4,
                'category_id' => 7,
                'created_at' => Carbon::now()->subDays(34),
                'updated_at' => Carbon::now()->subDays(34),
            ],
            [
                'title' => 'La Receta Perdida',
                'author_name' => 'Julieta Rossi',
                'content' => 'Una chef hereda el restaurante de su abuela y un libro de recetas incompleto que la lleva a un viaje por Italia.',
                'poster' => 'https://placehold.co/400x600/BE123C/FFFFFF/png?text=Receta+Perdida',
                'habilitated' => true,
                'stars' => 3,
                'category_id' => 6,
                'created_at' => Carbon::now()->subDays(35),
                'updated_at' => Carbon::now()->subDays(35),
            ],
            [
                'title' => 'El Bosque Susurrante',
                'author_name' => 'Anya Petrova',
                'content' => 'Cuentos de hadas eslavos reinventados con un toque oscuro y moderno. Cada historia es una joya macabra.',
                'poster' => 'https://placehold.co/400x600/3F6212/FFFFFF/png?text=Bosque+Susurrante',
                'habilitated' => true,
                'stars' => 5,
                'category_id' => 8,
                'created_at' => Carbon::now()->subDays(36),
                'updated_at' => Carbon::now()->subDays(36),
            ],
            [
                'title' => 'El Principio del Caos',
                'author_name' => 'Maximus Kane',
                'content' => 'Explora la teoría del caos y cómo pequeños eventos pueden tener consecuencias masivas en la ciencia y la sociedad.',
                'poster' => 'https://placehold.co/400x600/991B1B/FFFFFF/png?text=Principio+Caos',
                'habilitated' => true,
                'stars' => 4,
                'category_id' => 3,
                'created_at' => Carbon::now()->subDays(37),
                'updated_at' => Carbon::now()->subDays(37),
            ],
            [
                'title' => 'Poemas para Días de Lluvia',
                'author_name' => 'León Azul',
                'content' => 'Una colección melancólica y hermosa que captura perfectamente la sensación de una tarde lluviosa.',
                'poster' => 'https://placehold.co/400x600/53A0E4/FFFFFF/png?text=Poemas+Lluvia',
                'habilitated' => true,
                'stars' => 4,
                'category_id' => 10,
                'created_at' => Carbon::now()->subDays(38),
                'updated_at' => Carbon::now()->subDays(38),
            ],
            [
                'title' => 'El Arte de Estar Presente',
                'author_name' => 'Nia Sharma',
                'content' => 'Una guía práctica sobre mindfulness y meditación para reducir el estrés y aumentar la concentración en la era digital.',
                'poster' => 'https://placehold.co/400x600/34D399/000000/png?text=Arte+Presente',
                'habilitated' => true,
                'stars' => 5,
                'category_id' => 9,
                'created_at' => Carbon::now()->subDays(39),
                'updated_at' => Carbon::now()->subDays(39),
            ],
            [
                'title' => 'La Odisea del Pequeño Robot',
                'author_name' => 'Leo T. Clark',
                'content' => 'Un robot de juguete se pierde y debe viajar a través de un enorme jardín para volver con su niño. Una aventura tierna.',
                'poster' => 'https://placehold.co/400x600/FBBF24/000000/png?text=Pequeño+Robot',
                'habilitated' => true,
                'stars' => 4,
                'category_id' => 5,
                'created_at' => Carbon::now()->subDays(40),
                'updated_at' => Carbon::now()->subDays(40),
            ],
            [
                'title' => 'Código Cero',
                'author_name' => 'Alex Ryder',
                'content' => 'Una programadora descubre una puerta trasera en el software más seguro del mundo, atrayendo la atención de fuerzas peligrosas.',
                'poster' => 'https://placehold.co/400x600/0891B2/FFFFFF/png?text=Codigo+Cero',
                'habilitated' => true,
                'stars' => 4,
                'category_id' => 1,
                'created_at' => Carbon::now()->subDays(41),
                'updated_at' => Carbon::now()->subDays(41),
            ],
            [
                'title' => 'La Reina Olvidada',
                'author_name' => 'Helena P. Sinclair',
                'content' => 'La biografía de una reina borrada de la historia, cuyo reinado fue más influyente de lo que se creía.',
                'poster' => 'https://placehold.co/400x600/6D28D9/FFFFFF/png?text=Reina+Olvidada',
                'habilitated' => true,
                'stars' => 5,
                'category_id' => 4,
                'created_at' => Carbon::now()->subDays(42),
                'updated_at' => Carbon::now()->subDays(42),
            ],
            [
                'title' => 'Nuestro Universo Quántico',
                'author_name' => 'Dr. Kenji Tanaka',
                'content' => 'Una introducción amena a los misterios de la física cuántica, desde la dualidad onda-partícula hasta el entrelazamiento.',
                'poster' => 'https://placehold.co/400x600/047857/FFFFFF/png?text=Universo+Cuantico',
                'habilitated' => true,
                'stars' => 4,
                'category_id' => 3,
                'created_at' => Carbon::now()->subDays(43),
                'updated_at' => Carbon::now()->subDays(43),
            ],
            [
                'title' => 'El Secreto de la Isla Escondida',
                'author_name' => 'Samantha Jones',
                'content' => 'Dos hermanos encuentran un mapa antiguo que los lleva a una isla llena de enigmas y un tesoro pirata.',
                'poster' => 'https://placehold.co/400x600/D97706/FFFFFF/png?text=Isla+Escondida',
                'habilitated' => true,
                'stars' => 3,
                'category_id' => 7,
                'created_at' => Carbon::now()->subDays(44),
                'updated_at' => Carbon::now()->subDays(44),
            ],
            [
                'title' => 'Cartas que Nunca Envié',
                'author_name' => 'Anónimo',
                'content' => 'Una compilación de cartas de amor nunca entregadas, encontradas en un viejo baúl. Emotivo y agridulce.',
                'poster' => 'https://placehold.co/400x600/9333EA/FFFFFF/png?text=Cartas',
                'habilitated' => true,
                'stars' => 4,
                'category_id' => 6,
                'created_at' => Carbon::now()->subDays(45),
                'updated_at' => Carbon::now()->subDays(45),
            ],
            [
                'title' => 'La Rebelión de las Sombras',
                'author_name' => 'Nyx Umbra',
                'content' => 'En un mundo donde la luz es poder, las sombras cobran vida y luchan por su propia existencia. Fantasía oscura de alta calidad.',
                'poster' => 'https://placehold.co/400x600/1F2937/FFFFFF/png?text=Rebelion+Sombras',
                'habilitated' => true,
                'stars' => 5,
                'category_id' => 8,
                'created_at' => Carbon::now()->subDays(46),
                'updated_at' => Carbon::now()->subDays(46),
            ],
            [
                'title' => 'Minimalismo Digital',
                'author_name' => 'David Chen',
                'content' => 'Estrategias para organizar tu vida digital, reducir distracciones y usar la tecnología de forma intencional.',
                'poster' => 'https://placehold.co/400x600/4B5563/FFFFFF/png?text=Minimalismo',
                'habilitated' => true,
                'stars' => 4,
                'category_id' => 9,
                'created_at' => Carbon::now()->subDays(47),
                'updated_at' => Carbon::now()->subDays(47),
            ],
            [
                'title' => 'El Dragón de Papel',
                'author_name' => 'Mei Lin',
                'content' => 'Una niña aprende el antiguo arte del origami de su abuelo y descubre que sus creaciones pueden cobrar vida.',
                'poster' => 'https://placehold.co/400x600/DC2626/FFFFFF/png?text=Dragon+de+Papel',
                'habilitated' => true,
                'stars' => 5,
                'category_id' => 5,
                'created_at' => Carbon::now()->subDays(48),
                'updated_at' => Carbon::now()->subDays(48),
            ],
            [
                'title' => 'Haikus del Asfalto',
                'author_name' => 'Kaito',
                'content' => 'Breves poemas que capturan la belleza y la soledad de la vida urbana moderna. Observador y profundo.',
                'poster' => 'https://placehold.co/400x600/6B7280/FFFFFF/png?text=Haikus',
                'habilitated' => true,
                'stars' => 4,
                'category_id' => 10,
                'created_at' => Carbon::now()->subDays(49),
                'updated_at' => Carbon::now()->subDays(49),
            ],
            [
                'title' => 'Los Filósofos del Garaje',
                'author_name' => 'Saul Goodman',
                'content' => 'Relato de no ficción sobre cómo las grandes ideas tecnológicas del siglo XXI nacieron en los lugares más humildes.',
                'poster' => 'https://placehold.co/400x600/10B981/000000/png?text=Filosofos',
                'habilitated' => true,
                'stars' => 4,
                'category_id' => 2,
                'created_at' => Carbon::now()->subDays(50),
                'updated_at' => Carbon::now()->subDays(50),
            ],
        ];

        DB::table('posts')->insert($posts);
    }
}
